trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      echo "No build step required for static HTML. Copying files to artifact staging directory."
      mkdir -p $(Build.ArtifactStagingDirectory)
      cp -R * $(Build.ArtifactStagingDirectory)
    displayName: 'Prepare Static Files'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
